language: R
cache: packages
r: release
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
warnings_are_errors: false

env:
  global:
  - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
addons:
  apt:
    packages:
    - r-base-dev
    - r-recommended
    - libxml2-dev

before_install:
- tlmgr install index
before_deploy:
- echo "Tags are deployed to GitHub Releases for $R_PKG"

deploy:
  provider: releases
  api_key:
    secure: MxKbyWfTv2/b2EFRBd76+EVw//jx3j1HBVq6au8KOoZ7iIEj8cPfKwXUsycdvu9cZ5PMq+tQ47XSTAkzPeHndSMwEJ1uwQ1gOnAdkYhUrTKh+Ah/0WL+GoWydgMPo+m3w9wKB7ROCJpj7jXMDxDR2GS9Gql+zsTHGGBjMkKRpfKzq90s32aQIxVg2YEvkAW3drRqSKGFb8dyuFiyTj4BiOMWEPMC2pn1ODA3/J45vp+9mOFoJMKv8n+wFgQfj19sHXtFLp71MubvUx530aYXVetqcad0mEoIy1JYLdkP7ZXNXTiilEeaQ1rWiv7P8L42KyMh3ceX3I4UDaHdOqWKYNfcrU4F3/uaB4tTz0wUKUmUN/y2k8lp6K0pM7OXRjwVdW0zM3zfnHqzMoLZMLV/2anq71729ckyoTFggxcJG0XPXvZwqnaF3vKgY8Kh2WNwVY9PXouW35pP0aoG5dEVPDYMvnuLyFKaNEKE0hq8gC4sI0dPopX2ceb9Lk3W1tQbyIP4arPLabEGxhQ//BIFqgTLxkL9RnHt6jNa5gcIfFjUH2U2+m0z6QkOeGI5lHTQ2Q2gKd/VyRhG8s66Ngn5DIeTKaWFjK7cCyJcUGDfI00yfw4Yz9Vu9a1FpHUb0+/2YRRpi31+lYr/zeLykgDYwwFQvPS2dba4mmtm5i3TPOQ=
  file_glob: true
  file: ! "${R_PKG}_*.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    repo: GBIF-Europe/darwinator
    tags: true
